"""add email verification

Revision ID: aef98d1954d0
Revises: a70de92692c7
Create Date: 2026-09-14 20:03:28.883322
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aef98d1954d0"
down_revision: str | None = "a70de92692c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_token",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_verification_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_verification_token_token_hash"),
            ["token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_email_verification_token_user_id"), ["user_id"], unique=False
        )

    # ❗ Hand-corrected after autogenerate:
    #  - server defaults were emitted in SQLite dialect ("(false())",
    #    "(CURRENT_TIMESTAMP)"), which MySQL rejects. Replaced with the portable
    #    sa.false() / sa.func.now() constructs.
    #  - autogenerate also proposed alter_column on is_active/is_superuser.
    #    Those columns are unchanged; SQLite merely reports their defaults
    #    differently than the model declares, so the churn was dropped.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("verified_at")
        batch_op.drop_column("is_verified")

    with op.batch_alter_table("email_verification_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_verification_token_user_id"))
        batch_op.drop_index(batch_op.f("ix_email_verification_token_token_hash"))

    op.drop_table("email_verification_token")
    # ### end Alembic commands ###
